name: ShootingGallery
version: 'Patch-1.0.1'
main: run.tere.plugin.shootinggallery.ShootingGallery
api-version: 1.20
authors: [ tererun ]
description: ShootingGallery
commands:
  sg:
    description: shooting gallery main command